summary:
    path: /api/summary
    controller: App\Controller\SumController::makeSum
    methods: [POST]

getSummary:
  path: /api/get-summary
  controller: App\Controller\SumController::getLastsResults
  
